apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-appd-config
  labels:
    app: swagger-appd-tool
data:
  cm-appd-swagger-config.yaml: |-
{{ .Files.Get "k8s/cm-appd-swagger-config.yaml" | indent 4 }}