apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: swagger-appd-tool
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: swagger-appd-tool
  port:
    targetPort: http  # Musí odpovídat názvu portu definovaného ve službě
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect  # Přesměrování HTTP na HTTPS
