apiVersion: v1
kind: Service
metadata:
  name: swagger-appd-tool
  labels:
    app: swagger-appd-tool
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: swagger-appd-tool
